variables:
  DRUPAL_MODULE_NAME: commerce_klarna_payments
  SIMPLETEST_BASE_URL: http://127.0.0.1:8080
  DRUPAL_CORE_VERSION: 8.9.x
  DRUPAL_INSTALL_PROFILE: minimal
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal
  SIMPLETEST_DB: mysql://root:drupal@mariadb/drupal
  TEST_RUNNER: core
  SYMFONY_DEPRECATIONS_HELPER: disabled

before_script:
- export PATH=$HOME/.composer/vendor/bin:$PATH
- composer global require tuutti/drupal-test-runner ^1.0
- drupal-tr
- drupal-tr run-drush-server &

services:
- mariadb:latest

test:7.3:
  image: registry.gitlab.com/tuutti/drupal-php-docker:7.3
  script:
    - drupal-tr run-tests

test:7.4:
  image: registry.gitlab.com/tuutti/drupal-php-docker:7.4
  variables:
    DRUPAL_CORE_VERSION: 9.0.x
  script:
    - drupal-tr run-tests

test:8.0:
  image: registry.gitlab.com/tuutti/drupal-php-docker:8.0
  variables:
    DRUPAL_CORE_VERSION: 9.1.x
  script:
    - drupal-tr run-tests
