before_script:
- export PATH=$HOME/.composer/vendor/bin:$PATH
- composer global require tuutti/drupal-test-runner ^1.0
- drupal-tr

services:
- mariadb:latest

variables:
  DRUPAL_MODULE_NAME: commerce_klarna_payments
  DRUPAL_SERVER_HOST: http://127.0.0.1
  DRUPAL_SERVER_PORT: 8080
  DRUPAL_CORE: 8.9.x
  DRUPAL_INSTALL_PROFILE: minimal
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal
  SIMPLETEST_DB: mysql://root:drupal@mariadb/drupal
  TEST_RUNNER: core

test:7.1:
  image: registry.gitlab.com/tuutti/drupal-php-docker:7.1
  variables:
    DRUPAL_CORE: 8.8.x
  script:
    - drupal-tr run-tests

test:7.2:
  image: registry.gitlab.com/tuutti/drupal-php-docker:7.2
  script:
    - drupal-tr run-tests

test:7.3:
  image: registry.gitlab.com/tuutti/drupal-php-docker:7.3
  script:
    - drupal-tr run-tests

test:7.4:
  image: registry.gitlab.com/tuutti/drupal-php-docker:7.4
  variables:
    DRUPAL_CORE: 9.0.x
  script:
    - drupal-tr run-tests

