commerce_payment.commerce_payment_gateway.plugin.klarna_payments:
  type: commerce_payment_gateway_configuration
  mapping:
    locale:
      type: string
      label: 'Locale'
    username:
      type: string
      label: 'Merchant ID'
    password:
      type: string
      label: 'Merchant Authentication Hash'
    options:
      type: sequence
      label: 'Options'
      sequence:
        type: string
